[2025-01-11T22:14:03.509+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T22:14:03.522+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:08:57.094408+00:00 [queued]>
[2025-01-11T22:14:03.531+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:08:57.094408+00:00 [queued]>
[2025-01-11T22:14:03.532+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-11T22:14:03.545+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-11 22:08:57.094408+00:00
[2025-01-11T22:14:03.551+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-11T22:08:57.094408+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmpox116a42']
[2025-01-11T22:14:03.552+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask run_dbt_model
[2025-01-11T22:14:03.553+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-11T22:14:03.554+0000] {standard_task_runner.py:72} INFO - Started process 533 to run task
[2025-01-11T22:14:03.588+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:08:57.094408+00:00 [running]> on host a1d29b6e6d12
[2025-01-11T22:14:03.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T22:08:57.094408+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T22:08:57.094408+00:00'
[2025-01-11T22:14:03.651+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T22:14:07.994+0000] {logging_mixin.py:190} INFO - 22:14:05  Running with dbt=1.9.1
22:14:05  Registered adapter: postgres=1.9.0
22:14:06  Found 4 models, 2 seeds, 5 data tests, 2 sources, 546 macros
22:14:06  
22:14:06  Concurrency: 1 threads (target='dev')
22:14:06  
22:14:06  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
22:14:06  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.15s]
22:14:06  
22:14:06  Finished running 1 table model in 0 hours 0 minutes and 0.27 seconds (0.27s).
22:14:06  
22:14:06  Completed successfully
22:14:06  
22:14:06  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-11T22:14:07.995+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-11T22:14:08.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T22:14:08.005+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-11T22:08:57.094408+00:00, execution_date=20250111T220857, start_date=20250111T221403, end_date=20250111T221408
[2025-01-11T22:14:08.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-11T22:14:08.083+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T22:14:08.087+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
