[2025-01-11T22:04:50.158+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T22:04:50.184+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:04:49.823711+00:00 [queued]>
[2025-01-11T22:04:50.195+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:04:49.823711+00:00 [queued]>
[2025-01-11T22:04:50.195+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-11T22:04:50.208+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-11 22:04:49.823711+00:00
[2025-01-11T22:04:50.213+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-11T22:04:49.823711+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmp0hvy610l']
[2025-01-11T22:04:50.215+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-11T22:04:50.216+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask run_dbt_model
[2025-01-11T22:04:50.216+0000] {standard_task_runner.py:72} INFO - Started process 176 to run task
[2025-01-11T22:04:50.247+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-11T22:04:49.823711+00:00 [running]> on host 559442d12ea9
[2025-01-11T22:04:50.311+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T22:04:49.823711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T22:04:49.823711+00:00'
[2025-01-11T22:04:50.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T22:04:54.626+0000] {logging_mixin.py:190} INFO - 22:04:52  Running with dbt=1.9.1
22:04:52  Registered adapter: postgres=1.9.0
22:04:53  Found 4 models, 2 seeds, 5 data tests, 2 sources, 546 macros
22:04:53  
22:04:53  Concurrency: 1 threads (target='dev')
22:04:53  
22:04:53  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
22:04:53  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.11s]
22:04:53  
22:04:53  Finished running 1 table model in 0 hours 0 minutes and 0.26 seconds (0.26s).
22:04:53  
22:04:53  Completed successfully
22:04:53  
22:04:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-11T22:04:54.627+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-11T22:04:54.635+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T22:04:54.635+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-11T22:04:49.823711+00:00, execution_date=20250111T220449, start_date=20250111T220450, end_date=20250111T220454
[2025-01-11T22:04:54.654+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-11T22:04:54.665+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T22:04:54.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
